export const roleMeta = {
  patient: {
    key: "patient",
    label: "患者端",
    color: "#0ea5a4",
    homePath: "/patient/dashboard",
  },
  doctor: {
    key: "doctor",
    label: "医生端",
    color: "#2563eb",
    homePath: "/doctor/dashboard",
  },
  admin: {
    key: "admin",
    label: "管理员端",
    color: "#b45309",
    homePath: "/admin/dashboard",
  },
};

export const roleMenus = {
  patient: [
    {
      key: "dashboard",
      title: "工作台",
      path: "/patient/dashboard",
      icon: "DataBoard",
      children: ["今日预约", "待缴费", "最新报告"],
    },
    {
      key: "appointments",
      title: "预约挂号",
      path: "/patient/appointments",
      icon: "Calendar",
      children: ["医生排班查询", "新建预约", "我的预约", "退号/改约"],
    },
    {
      key: "visits",
      title: "就诊记录",
      path: "/patient/visits",
      icon: "Tickets",
      children: ["门诊记录列表", "就诊详情"],
    },
    {
      key: "reports",
      title: "检验检查报告",
      path: "/patient/reports",
      icon: "Document",
      children: ["报告列表", "报告详情/打印"],
    },
    {
      key: "prescriptions",
      title: "处方与药品",
      path: "/patient/prescriptions",
      icon: "Memo",
      children: ["处方列表", "处方详情"],
    },
    {
      key: "payments",
      title: "缴费中心",
      path: "/patient/payments",
      icon: "Wallet",
      children: ["待支付账单", "支付记录", "发票下载"],
    },
  ],
  doctor: [
    {
      key: "dashboard",
      title: "医生工作台",
      path: "/doctor/dashboard",
      icon: "Monitor",
      children: ["今日排班", "候诊队列", "待处理事项"],
    },
    {
      key: "clinic",
      title: "门诊接诊",
      path: "/doctor/clinic",
      icon: "User",
      children: ["候诊列表", "接诊中", "已完成"],
    },
    {
      key: "records",
      title: "病历管理",
      path: "/doctor/records",
      icon: "DocumentCopy",
      children: ["新建病历", "病历编辑", "病历归档查询"],
    },
    {
      key: "orders",
      title: "医嘱与处方",
      path: "/doctor/orders",
      icon: "EditPen",
      children: ["开立处方", "检验检查申请", "历史医嘱查询"],
    },
    {
      key: "patients",
      title: "患者管理",
      path: "/doctor/patients",
      icon: "Avatar",
      children: ["患者列表", "患者详情（历史就诊/过敏史/用药史）"],
    },
    {
      key: "schedule",
      title: "我的排班",
      path: "/doctor/schedule",
      icon: "Clock",
      children: ["班次查看", "请假/调班申请"],
    },
  ],
  admin: [
    {
      key: "dashboard",
      title: "运营总览",
      path: "/admin/dashboard",
      icon: "PieChart",
      children: ["挂号与接诊统计", "收费与医保统计", "药房库存预警"],
    },
    {
      key: "org",
      title: "组织与人员",
      path: "/admin/org",
      icon: "OfficeBuilding",
      children: ["科室管理", "医生/护士/职员管理", "患者账号管理"],
    },
    {
      key: "auth",
      title: "权限中心",
      path: "/admin/auth",
      icon: "Lock",
      children: ["角色管理", "菜单权限", "数据权限策略"],
    },
    {
      key: "scheduling",
      title: "排班与号源",
      path: "/admin/scheduling",
      icon: "Calendar",
      children: ["排班配置", "号源规则", "停诊与调班处理"],
    },
    {
      key: "pharmacy",
      title: "药房与库存",
      path: "/admin/pharmacy",
      icon: "Box",
      children: ["药品目录", "库存管理", "出入库记录"],
    },
    {
      key: "billing",
      title: "收费与医保",
      path: "/admin/billing",
      icon: "Coin",
      children: ["收费项目配置", "医保对账", "异常账单处理"],
    },
    {
      key: "reports",
      title: "报表中心",
      path: "/admin/reports",
      icon: "TrendCharts",
      children: ["业务报表", "财务报表", "导出下载"],
    },
    {
      key: "system",
      title: "系统管理",
      path: "/admin/system",
      icon: "Setting",
      children: ["参数配置", "字典管理", "操作日志", "审计日志"],
    },
  ],
};
