server.port=8080
spring.application.name=patient-appointments-backend
spring.main.banner-mode=off
spring.datasource.url=jdbc:h2:file:./data/hospital-demo;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.h2.console.enabled=true
demo.auth.token-hours=24